# See https://github.com/probot/settings
repository:
  private: true
  has_issues: true
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: false

teams:
  - name: pno
    permission: admin
  - name: run
    permission: push
